<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="3" hostname="DESKTOP-5EVK54D" failures="1" tests="2" name="Default test(failed)" time="0.155" errors="0" timestamp="2022-12-21T08:10:46 IST">
  <testcase classname="testngdiscussion.FailedTestCaseExecution" name="home" time="0.032">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at testngdiscussion.FailedTestCaseExecution.home(FailedTestCaseExecution.java:19)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- home -->
  <testcase classname="testngdiscussion.FailedTestCaseExecution" name="timeline" time="0.0">
    <skipped/>
  </testcase> <!-- timeline -->
  <testcase classname="testngdiscussion.FailedTestCaseExecution" name="login" time="0.0">
    <ignored/>
  </testcase> <!-- login -->
  <testcase classname="testngdiscussion.FailedTestCaseExecution" name="profile" time="0.0">
    <ignored/>
  </testcase> <!-- profile -->
  <testcase classname="testngdiscussion.FailedTestCaseExecution" name="logout" time="0.0">
    <ignored/>
  </testcase> <!-- logout -->
</testsuite> <!-- Default test(failed) -->
